/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void nombre_change(GTextField source, GEvent event) { //_CODE_:nombre:744957:
  println("nombre - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:nombre:744957:

public void textfield2_change1(GTextField source, GEvent event) { //_CODE_:email:380906:
  println("email - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:email:380906:

public void reg_click2(GButton source, GEvent event) { //_CODE_:registrar:874211:
  println("registrar - GButton >> GEvent." + event + " @ " + millis());
  String Nombre = nombre.getText();
  String Correo = email.getText();
  elusuario = new Usuario(Nombre, idreg, Correo, msql);
  inicio();
} //_CODE_:registrar:874211:

public void pedir_click1(GButton source, GEvent event) { //_CODE_:Pedir:223393:
  println("Pedir - GButton >> GEvent." + event + " @ " + millis());
  elusuario.askfBike();
  println("pidio");
  inicio();
} //_CODE_:Pedir:223393:

public void devolver_click1(GButton source, GEvent event) { //_CODE_:Devolver:670841:
  println("Devolver - GButton >> GEvent." + event + " @ " + millis());
  elusuario.returnBike();
  println("devolvio");
  inicio();
} //_CODE_:Devolver:670841:

public void siguiente(GButton source, GEvent event) { //_CODE_:sig:519522:
  println("sig - GButton >> GEvent." + event + " @ " + millis());
  Registro();
  println("ddd");
} //_CODE_:sig:519522:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  Inicio = new GLabel(this, 188, 236, 600, 150);
  Inicio.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  Inicio.setText("Bienvenido, por favor presione siguiente y acerque su carné en el lector");
  Inicio.setTextBold();
  Inicio.setOpaque(false);
  nombre = new GTextField(this, 540, 372, 200, 40, G4P.SCROLLBARS_NONE);
  nombre.setOpaque(true);
  nombre.addEventHandler(this, "nombre_change");
  email = new GTextField(this, 542, 479, 200, 40, G4P.SCROLLBARS_NONE);
  email.setPromptText("example@unal.edu.co");
  email.setOpaque(true);
  email.addEventHandler(this, "textfield2_change1");
  registrar = new GButton(this, 402, 598, 170, 60);
  registrar.setText("Regitrar");
  registrar.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  registrar.addEventHandler(this, "reg_click2");
  nom = new GLabel(this, 196, 352, 300, 80);
  nom.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  nom.setText("Por favor ingrese su nombre:");
  nom.setOpaque(false);
  corr = new GLabel(this, 197, 462, 300, 80);
  corr.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  corr.setText("Por favor ingrese su correo UNal:");
  corr.setOpaque(false);
  Pedir = new GButton(this, 335, 340, 300, 100);
  Pedir.setText("Pedir Bbcicleta");
  Pedir.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  Pedir.addEventHandler(this, "pedir_click1");
  Devolver = new GButton(this, 336, 354, 300, 100);
  Devolver.setText("Devolver");
  Devolver.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  Devolver.addEventHandler(this, "devolver_click1");
  sig = new GButton(this, 336, 606, 300, 100);
  sig.setText("Siguiente");
  sig.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  sig.addEventHandler(this, "siguiente");
}

// Variable declarations 
// autogenerated do not edit
GLabel Inicio; 
GTextField nombre; 
GTextField email; 
GButton registrar; 
GLabel nom; 
GLabel corr; 
GButton Pedir; 
GButton Devolver; 
GButton sig; 