/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.
 
 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
 // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void nombre_change(GTextField source, GEvent event) { //_CODE_:nombre:447644:
  println("nombre - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:nombre:447644:

public void email_change1(GTextField source, GEvent event) { //_CODE_:email:330141:
  println("email - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:email:330141:

public void registrar_click(GButton source, GEvent event) { //_CODE_:registrar:596100:
  println("registrar - GButton >> GEvent." + event + " @ " + millis());
  String Nombre = nombre.getText();
  String Correo = email.getText();
  elusuario = new Usuario(Nombre, idreg, Correo, msql);
  inicio();
} //_CODE_:registrar:596100:

public void Pedir_click1(GButton source, GEvent event) { //_CODE_:Pedir:686565:
  println("Pedir - GButton >> GEvent." + event + " @ " + millis());
  msql.query("SELECT `NombreEstacion` FROM `estaciones` WHERE `NombreEstacion` <> '"+CurrentStation+"'");
  ListaEstacionesD = "Seleccionar Estacion";
  println(ListaEstacionesD);
  while (msql.next()==true) {
    String ListaEstacionestmp = msql.getString(1);
    ListaEstacionesD = ListaEstacionesD+","+ListaEstacionestmp;
    println(ListaEstacionesD);
  }
  ListaD = splitTokens(ListaEstacionesD, ",");
  printArray(ListaD);
  destino.setItems(ListaD, 0);
  Pedir.setVisible(false);
  preg.setVisible(false);
  destino.setVisible(true);
  dest.setVisible(true);
} //_CODE_:Pedir:686565:

public void devolver_click(GButton source, GEvent event) { //_CODE_:Devolver:920879:
  println("Devolver - GButton >> GEvent." + event + " @ " + millis());
  bici.returnBike();
  NumBici.setText(elusuario.Nombre+" has devuelto la bicicleta número: "+ bici.Number);
  Devolver.setVisible(false);
  preg.setVisible(false);
  NumBici.setVisible(true);
  ok.setVisible(true);
} //_CODE_:Devolver:920879:

public void siguiente_click(GButton source, GEvent event) { //_CODE_:sig:625524:
  println("sig - GButton >> GEvent." + event + " @ " + millis());
  Registro();
} //_CODE_:sig:625524:

public void ok_click1(GButton source, GEvent event) { //_CODE_:ok:844847:
  println("ok - GButton >> GEvent." + event + " @ " + millis());
  inicio();
} //_CODE_:ok:844847:

public void Estaciones1_click1(GDropList source, GEvent event) { //_CODE_:Estaciones1:259145:
  println("Estaciones1 - GDropList >> GEvent." + event + " @ " + millis());

  CurrentStation = Estaciones1.getSelectedText ();
  println(CurrentStation);
  station = new Estacion(msql);
  //CurrentStation = station.NameStation;
  IdCurrentStation = station.id_estacion;
  adm.setVisible(false);
  Estaciones1.setVisible(false);
  println("Sali");
  inicio();
} //_CODE_:Estaciones1:259145:

public void destino_click1(GDropList source, GEvent event) { //_CODE_:destino:382050:
  println("destino - GDropList >> GEvent." + event + " @ " + millis());
  String llegada = destino.getSelectedText ();
  bici.assignBike(llegada);
  NumBici.setText(elusuario.Nombre +" toma la bicicleta número: "+ bici.Number);
  destino.setSelected(0);
  destino.setVisible(false);
  dest.setVisible(false);
  NumBici.setVisible(true);
  ok.setVisible(true);
} //_CODE_:destino:382050:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI() {
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  Inicio = new GLabel(this, 69, 228, 700, 160);
  Inicio.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  Inicio.setText("Bienvenido, por favor presione siguiente y acerque su carné al lector");
  Inicio.setLocalColorScheme(GCScheme.SCHEME_10);
  Inicio.setOpaque(false);
  nombre = new GTextField(this, 508, 348, 250, 45, G4P.SCROLLBARS_NONE);
  nombre.setPromptText("Nombre");
  nombre.setLocalColorScheme(GCScheme.SCHEME_10);
  nombre.setOpaque(true);
  nombre.addEventHandler(this, "nombre_change");
  email = new GTextField(this, 521, 480, 250, 45, G4P.SCROLLBARS_NONE);
  email.setLocalColorScheme(GCScheme.SCHEME_10);
  email.setOpaque(true);
  email.addEventHandler(this, "email_change1");
  registrar = new GButton(this, 350, 618, 140, 70);
  registrar.setText("Registrar");
  registrar.setLocalColorScheme(GCScheme.SCHEME_9);
  registrar.addEventHandler(this, "registrar_click");
  nom = new GLabel(this, 57, 327, 400, 100);
  nom.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  nom.setText("Ingrese su nombre:");
  nom.setLocalColorScheme(GCScheme.SCHEME_10);
  nom.setOpaque(false);
  corr = new GLabel(this, 58, 462, 400, 100);
  corr.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  corr.setText("Ingrse su correo Unal: ");
  corr.setLocalColorScheme(GCScheme.SCHEME_10);
  corr.setOpaque(false);
  Pedir = new GButton(this, 314, 483, 300, 100);
  Pedir.setText("Pedir bicicleta");
  Pedir.setLocalColorScheme(GCScheme.SCHEME_9);
  Pedir.addEventHandler(this, "Pedir_click1");
  Devolver = new GButton(this, 314, 477, 300, 100);
  Devolver.setText("Devolver bicicleta");
  Devolver.setLocalColorScheme(GCScheme.SCHEME_9);
  Devolver.addEventHandler(this, "devolver_click");
  sig = new GButton(this, 272, 516, 350, 120);
  sig.setText("Siguiente");
  sig.setLocalColorScheme(GCScheme.SCHEME_9);
  sig.addEventHandler(this, "siguiente_click");
  NumBici = new GLabel(this, 114, 240, 600, 170);
  NumBici.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  NumBici.setLocalColorScheme(GCScheme.SCHEME_10);
  NumBici.setOpaque(false);
  ok = new GButton(this, 402, 563, 300, 90);
  ok.setText("Ok");
  ok.setLocalColorScheme(GCScheme.SCHEME_9);
  ok.addEventHandler(this, "ok_click1");
  preg = new GLabel(this, 142, 294, 550, 100);
  preg.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  preg.setText("¿Desea pedir una bicicleta?");
  preg.setLocalColorScheme(GCScheme.SCHEME_10);
  preg.setOpaque(false);
  Nodis = new GLabel(this, 134, 289, 550, 120);
  Nodis.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  Nodis.setText("Lo sentimos, no hay bicicletas disponibles.");
  Nodis.setLocalColorScheme(GCScheme.SCHEME_10);
  Nodis.setOpaque(false);
  Estaciones1 = new GDropList(this, 286, 420, 250, 200, 4);
  Estaciones1.setLocalColorScheme(GCScheme.SCHEME_10);
  Estaciones1.addEventHandler(this, "Estaciones1_click1");
  adm = new GLabel(this, 91, 257, 600, 150);
  adm.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  adm.setText("Bienvenido administrador, Seleccione la estación en la que se encuentra:");
  adm.setLocalColorScheme(GCScheme.SCHEME_10);
  adm.setOpaque(false);
  destino = new GDropList(this, 288, 442, 250, 200, 4);
  //destino.setItems(loadStrings("list_382050"), 0);
  destino.setLocalColorScheme(GCScheme.SCHEME_10);
  destino.addEventHandler(this, "destino_click1");
  dest = new GLabel(this, 109, 237, 580, 120);
  dest.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  dest.setText("Por favor seleccione su destino: ");
  dest.setLocalColorScheme(GCScheme.SCHEME_10);
  dest.setOpaque(false);
}

// Variable declarations 
// autogenerated do not edit
GLabel Inicio; 
GTextField nombre; 
GTextField email; 
GButton registrar; 
GLabel nom; 
GLabel corr; 
GButton Pedir; 
GButton Devolver; 
GButton sig; 
GLabel NumBici; 
GButton ok; 
GLabel preg; 
GLabel Nodis; 
GDropList Estaciones1; 
GLabel adm; 
GDropList destino; 
GLabel dest; 